
theme: jekyll-theme-minimal
title: HeartyPatch Documentation
twitter_username: protocentral
github_username:  protocentral
description: "HeartyPatch is a completely open source, single-lead, ECG-HR wearable patch with HRV (Heart Rate Variability) analysis. It is based on the popular ESP32 system-on-a-chip."

